services:
  - type: web
    name: backend
    env: node
    buildCommand: npm install && cd admin && npm install && npm run build && cd .. && mkdir -p dist && cp -r admin/dist/* dist/
    startCommand: node index.js
    healthCheckPath: /api/config/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: VNP_TMNCODE
        sync: false
      - key: VNP_HASHSECRET
        sync: false
      - key: VNP_URL
        value: https://sandbox.vnpayment.vn
      - key: VNP_TEST_MODE
        value: true
      - key: APP_URL
        value: https://tuelord.site
      - key: FRONTEND_URL
        value: https://tuelord.site
